# Generated by Django 2.0.4 on 2019-04-16 11:47

from django.db import migrations, models
import django.db.models.deletion
import helpful.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('alt', models.CharField(max_length=255, verbose_name='Alt')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('img', models.FileField(blank=True, null=True, upload_to=helpful.fields.upload_to, verbose_name='Image')),
                ('url', models.CharField(max_length=1024, verbose_name='URL')),
                ('sort', models.PositiveSmallIntegerField(default=500, verbose_name='Sort')),
                ('often', models.PositiveSmallIntegerField(choices=[[0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10]], help_text='A ten will display 10 times more often that a one.', verbose_name='Often')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('flash', 'Flash'), ('html', 'HTML')], default='image', max_length=32, verbose_name='URL')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('width', models.PositiveSmallIntegerField(default=0, verbose_name='Width')),
                ('height', models.PositiveSmallIntegerField(default=0, verbose_name='Height')),
                ('speed', models.PositiveSmallIntegerField(default=2000, verbose_name='Speed')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Banner Group',
                'verbose_name_plural': 'Banner Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('url', models.CharField(max_length=2048, verbose_name='URL or URL RegEx')),
                ('regex', models.BooleanField(default=False, verbose_name='RegEx')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sites', models.ManyToManyField(blank=True, related_name='site_urls', to='sites.Site', verbose_name='Sites')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='banners.BannerGroup', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='banner',
            name='urls',
            field=models.ManyToManyField(blank=True, related_name='url_banners', to='banners.URL', verbose_name='URLs'),
        ),
    ]
