# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_auto_20160301_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='urls',
            field=models.ManyToManyField(blank=True, related_name='url_banners', to='banners.URL', verbose_name='URLs'),
        ),
    ]
