# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import helpful.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_auto_20160311_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=helpful.fields.upload_to, verbose_name='Image'),
        ),
    ]
